### ISSUE TITLE
你好我是 iconfont 的开发者

### ISSUE THREAD

**Issue by yisibl** [NitroRCr/coolapk-emotion#1]
这个表情包画的非常不错！

我可以把这个表情包放到 iconfont 的图标库和相关介绍文章里吗，会注明原作者和链接，主要用于展示新的彩色字体功能。

iconfont 即将上线全新的彩色字体图标，比 SVG 拥有更好的性能和更小的体积。

**Comment by NitroRCr** [comment]
可以的。
感谢支持！
